import numpy as np
from prepro import *
from config import *

config = get_config()

    #####  pre-process #####

    # read data
data, max_len_context, max_len_question = read_data(config)

    
    # write a word dictionary
wordic = write_wordic(config, data['train'])

text = [['in', '2007', 'two', 'faa', 'whistleblowers', 'inspectors', 'charalambe', 'bobby',
'boutris', 'and', 'douglas', 'e', 'peters', 'alleged', 'that', 'boutris', 'said', 'he', 'attempted',
'to', 'ground', 'southwest', 'after', 'finding', 'cracks', 'in', 'fuselage', 'but', 'was',
'prevented', 'by', 'supervisors', 'he', 'said', 'were', 'friendly', 'with', 'airline', 'this',
'was', 'validated', 'by', 'report', 'by', 'department', 'of', 'transportation', 'which', 'found',
'faa', 'managers', 'had', 'allowed', 'southwest', 'airlines', 'to', 'fly', '46', 'airplanes', 'in',
'2006', 'and', '2007', 'that', 'were', 'overdue', 'for', 'safety', 'inspections', 'ignoring',
'concerns', 'raised', 'by', 'inspectors', 'audits', 'of', 'other', 'airlines', 'resulted', 'in',
'two', 'airlines', 'grounding', 'hundreds', 'of', 'planes', 'causing', 'thousands', 'of', 'flight',
'cancellations', 'house', 'transportation', 'and', 'infrastructure', 'committee', 'held',
'hearings', 'in', 'april', '2008', 'jim', 'oberstar', 'former', 'chairman', 'of', 'committee',
'said', 'its', 'investigation', 'uncovered', 'pattern', 'of', 'regulatory', 'abuse', 'and',
'widespread', 'regulatory', 'lapses', 'allowing', '117', 'aircraft', 'to', 'be', 'operated',
'commercially', 'although', 'not', 'in', 'compliance', 'with', 'faa', 'safety', 'rules', 'oberstar',
'said', 'there', 'was', 'culture', 'of', 'coziness', 'between', 'senior', 'faa', 'officials', 'and',
'airlines', 'and', 'systematic', 'breakdown', 'in', 'faas', 'culture', 'that', 'resulted', 'in',
'malfeasance', 'bordering', 'on', 'corruption', 'in', '2008', 'faa', 'proposed', 'to', 'fine',
'southwest', '102', 'million', 'for', 'failing', 'to', 'inspect', 'older', 'planes', 'for',
'cracks', 'and', 'in', '2009', 'southwest', 'and', 'faa', 'agreed', 'that', 'southwest', 'would',
'pay', '75', 'million', 'penalty', 'and', 'would', 'adopt', 'new', 'safety', 'procedures', 'with',
'fine', 'doubling', 'if', 'southwest', 'failed', 'to', 'follow', 'through', '$PAD$', '$PAD$',
'$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$',
'$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$',
'$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$',
'$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$',
'$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$',
'$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$',
'$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$',
'$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$',
'$PAD$', '$PAD$', '$PAD$', '$PAD$'], ['on', 'july', '22', '2008', 'in', 'aftermath', 'of',
'southwest', 'airlines', 'inspection', 'scandal', 'bill', 'was', 'unanimously', 'approved', 'in',
'house', 'to', 'tighten', 'regulations', 'concerning', 'airplane', 'maintenance', 'procedures',
'including', 'establishment', 'of', 'whistleblower', 'office', 'and', 'twoyear', 'cooling', 'off',
'period', 'that', 'faa', 'inspectors', 'or', 'supervisors', 'of', 'inspectors', 'must', 'wait',
'before', 'they', 'can', 'work', 'for', 'those', 'they', 'regulated', 'bill', 'also', 'required',
'rotation', 'of', 'principal', 'maintenance', 'inspectors', 'and', 'stipulated', 'that', 'word',
'customer', 'properly', 'applies', 'to', 'flying', 'public', 'not', 'those', 'entities',
'regulated', 'by', 'faa', 'bill', 'died', 'in', 'senate', 'committee', 'that', 'year', '$PAD$',
'$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$',
'$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$',
'$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$',
'$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$',
'$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$',
'$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$',
'$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$',
'$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$',
'$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$',
'$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$',
'$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$',
'$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$',
'$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$',
'$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$',
'$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$',
'$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$',
'$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$',
'$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$',
'$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$',
'$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$'], ['on', 'july', '22',
'2008', 'in', 'aftermath', 'of', 'southwest', 'airlines', 'inspection', 'scandal', 'bill', 'was',
'unanimously', 'approved', 'in', 'house', 'to', 'tighten', 'regulations', 'concerning', 'airplane',
'maintenance', 'procedures', 'including', 'establishment', 'of', 'whistleblower', 'office', 'and',
'twoyear', 'cooling', 'off', 'period', 'that', 'faa', 'inspectors', 'or', 'supervisors', 'of',
'inspectors', 'must', 'wait', 'before', 'they', 'can', 'work', 'for', 'those', 'they', 'regulated',
'bill', 'also', 'required', 'rotation', 'of', 'principal', 'maintenance', 'inspectors', 'and',
'stipulated', 'that', 'word', 'customer', 'properly', 'applies', 'to', 'flying', 'public', 'not',
'those', 'entities', 'regulated', 'by', 'faa', 'bill', 'died', 'in', 'senate', 'committee', 'that',
'year', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$',
'$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$',
'$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$',
'$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$',
'$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$',
'$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$',
'$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$',
'$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$',
'$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$',
'$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$',
'$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$',
'$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$',
'$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$',
'$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$',
'$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$',
'$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$',
'$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$',
'$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$',
'$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$',
'$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$'], ['on',
'july', '22', '2008', 'in', 'aftermath', 'of', 'southwest', 'airlines', 'inspection', 'scandal',
'bill', 'was', 'unanimously', 'approved', 'in', 'house', 'to', 'tighten', 'regulations',
'concerning', 'airplane', 'maintenance', 'procedures', 'including', 'establishment', 'of',
'whistleblower', 'office', 'and', 'twoyear', 'cooling', 'off', 'period', 'that', 'faa',
'inspectors', 'or', 'supervisors', 'of', 'inspectors', 'must', 'wait', 'before', 'they', 'can',
'work', 'for', 'those', 'they', 'regulated', 'bill', 'also', 'required', 'rotation', 'of',
'principal', 'maintenance', 'inspectors', 'and', 'stipulated', 'that', 'word', 'customer',
'properly', 'applies', 'to', 'flying', 'public', 'not', 'those', 'entities', 'regulated', 'by',
'faa', 'bill', 'died', 'in', 'senate', 'committee', 'that', 'year', '$PAD$', '$PAD$', '$PAD$',
'$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$',
'$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$',
'$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$',
'$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$',
'$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$',
'$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$',
'$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$',
'$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$',
'$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$',
'$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$',
'$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$',
'$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$',
'$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$',
'$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$',
'$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$',
'$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$',
'$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$',
'$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$',
'$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$',
'$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$']]


text = [['i','he','you'],['i','he','you'],['i','she','me']]

text = [['emotions', 'are', 'complex', 'according', 'to', 'some', 'theories', 'they', 'are',
'state', 'of', 'feeling', 'that', 'results', 'in', 'physical', 'and', 'psychological', 'changes',
'that', 'influence', 'our', 'behavior', 'physiology', 'of', 'emotion', 'is', 'closely', 'linked',
'to', 'arousal', 'of', 'nervous', 'system', 'with', 'various', 'states', 'and', 'strengths', 'of',
'arousal', 'relating', 'apparently', 'to', 'particular', 'emotions', 'emotion', 'is', 'also',
'linked', 'to', 'behavioral', 'tendency', 'extroverted', 'people', 'are', 'more', 'likely', 'to',
'be', 'social', 'and', 'express', 'their', 'emotions', 'while', 'introverted', 'people', 'are',
'more', 'likely', 'to', 'be', 'more', 'socially', 'withdrawn', 'and', 'conceal', 'their',
'emotions', 'emotion', 'is', 'often', 'driving', 'force', 'behind', 'motivation', 'positive', 'or',
'negative', 'definition', 'has', 'been', 'described', 'as', 'is', 'positive', 'or', 'negative',
'experience', 'that', 'is', 'associated', 'with', 'particular', 'pattern', 'of', 'physiological',
'activity', 'according', 'to', 'other', 'theories', 'emotions', 'are', 'not', 'causal', 'forces',
'but', 'simply', 'syndromes', 'of', 'components', 'which', 'might', 'include', 'motivation',
'feeling', 'behavior', 'and', 'physiological', 'changes', 'but', 'no', 'one', 'of', 'these',
'components', 'is', 'emotion', 'nor', 'is', 'emotion', 'entity', 'that', 'causes', 'these',
'components', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$',
'$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$',
'$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$',
'$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$',
'$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$',
'$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$',
'$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$',
'$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$',
'$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$',
'$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$',
'$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$',
'$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$',
'$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$',
'$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$'],
['emotions', 'are', 'complex', 'according', 'to', 'some', 'theories', 'they', 'are', 'state', 'of',
    'feeling', 'that', 'results', 'in', 'physical', 'and', 'psychological', 'changes', 'that',
    'influence', 'our', 'behavior', 'physiology', 'of', 'emotion', 'is', 'closely', 'linked', 'to',
    'arousal', 'of', 'nervous', 'system', 'with', 'various', 'states', 'and', 'strengths', 'of',
    'arousal', 'relating', 'apparently', 'to', 'particular', 'emotions', 'emotion', 'is', 'also',
    'linked', 'to', 'behavioral', 'tendency', 'extroverted', 'people', 'are', 'more', 'likely',
    'to', 'be', 'social', 'and', 'express', 'their', 'emotions', 'while', 'introverted', 'people',
    'are', 'more', 'likely', 'to', 'be', 'more', 'socially', 'withdrawn', 'and', 'conceal', 'their',
    'emotions', 'emotion', 'is', 'often', 'driving', 'force', 'behind', 'motivation', 'positive',
    'or', 'negative', 'definition', 'has', 'been', 'described', 'as', 'is', 'positive', 'or',
    'negative', 'experience', 'that', 'is', 'associated', 'with', 'particular', 'pattern', 'of',
    'physiological', 'activity', 'according', 'to', 'other', 'theories', 'emotions', 'are', 'not',
    'causal', 'forces', 'but', 'simply', 'syndromes', 'of', 'components', 'which', 'might',
    'include', 'motivation', 'feeling', 'behavior', 'and', 'physiological', 'changes', 'but', 'no',
    'one', 'of', 'these', 'components', 'is', 'emotion', 'nor', 'is', 'emotion', 'entity', 'that',
    'causes', 'these', 'components', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$',
    '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$',
    '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$',
    '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$',
    '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$',
    '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$',
    '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$',
    '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$',
    '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$',
    '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$',
    '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$',
    '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$',
    '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$',
    '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$',
    '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$',
    '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$'], ['emotions', 'are', 'complex', 'according', 'to',
            'some', 'theories', 'they', 'are', 'state', 'of', 'feeling', 'that', 'results', 'in',
            'physical', 'and', 'psychological', 'changes', 'that', 'influence', 'our', 'behavior',
            'physiology', 'of', 'emotion', 'is', 'closely', 'linked', 'to', 'arousal', 'of',
            'nervous', 'system', 'with', 'various', 'states', 'and', 'strengths', 'of', 'arousal',
            'relating', 'apparently', 'to', 'particular', 'emotions', 'emotion', 'is', 'also',
            'linked', 'to', 'behavioral', 'tendency', 'extroverted', 'people', 'are', 'more',
            'likely', 'to', 'be', 'social', 'and', 'express', 'their', 'emotions', 'while',
            'introverted', 'people', 'are', 'more', 'likely', 'to', 'be', 'more', 'socially',
            'withdrawn', 'and', 'conceal', 'their', 'emotions', 'emotion', 'is', 'often', 'driving',
            'force', 'behind', 'motivation', 'positive', 'or', 'negative', 'definition', 'has',
            'been', 'described', 'as', 'is', 'positive', 'or', 'negative', 'experience', 'that',
            'is', 'associated', 'with', 'particular', 'pattern', 'of', 'physiological', 'activity',
            'according', 'to', 'other', 'theories', 'emotions', 'are', 'not', 'causal', 'forces',
            'but', 'simply', 'syndromes', 'of', 'components', 'which', 'might', 'include',
            'motivation', 'feeling', 'behavior', 'and', 'physiological', 'changes', 'but', 'no',
            'one', 'of', 'these', 'components', 'is', 'emotion', 'nor', 'is', 'emotion', 'entity',
            'that', 'causes', 'these', 'components', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$',
            '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$',
            '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$',
            '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$',
            '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$',
            '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$',
            '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$',
            '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$',
            '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$',
            '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$',
            '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$',
            '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$',
            '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$',
            '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$',
            '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$',
            '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$',
            '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$',
            '$PAD$', '$PAD$', '$PAD$'], ['emotions', 'are', 'complex', 'according', 'to', 'some',
                    'theories', 'they', 'are', 'state', 'of', 'feeling', 'that', 'results', 'in',
                    'physical', 'and', 'psychological', 'changes', 'that', 'influence', 'our',
                    'behavior', 'physiology', 'of', 'emotion', 'is', 'closely', 'linked', 'to',
                    'arousal', 'of', 'nervous', 'system', 'with', 'various', 'states', 'and',
                    'strengths', 'of', 'arousal', 'relating', 'apparently', 'to', 'particular',
                    'emotions', 'emotion', 'is', 'also', 'linked', 'to', 'behavioral', 'tendency',
                    'extroverted', 'people', 'are', 'more', 'likely', 'to', 'be', 'social', 'and',
                    'express', 'their', 'emotions', 'while', 'introverted', 'people', 'are', 'more',
                    'likely', 'to', 'be', 'more', 'socially', 'withdrawn', 'and', 'conceal',
                    'their', 'emotions', 'emotion', 'is', 'often', 'driving', 'force', 'behind',
                    'motivation', 'positive', 'or', 'negative', 'definition', 'has', 'been',
                    'described', 'as', 'is', 'positive', 'or', 'negative', 'experience', 'that',
                    'is', 'associated', 'with', 'particular', 'pattern', 'of', 'physiological',
                    'activity', 'according', 'to', 'other', 'theories', 'emotions', 'are', 'not',
                    'causal', 'forces', 'but', 'simply', 'syndromes', 'of', 'components', 'which',
                    'might', 'include', 'motivation', 'feeling', 'behavior', 'and', 'physiological',
                    'changes', 'but', 'no', 'one', 'of', 'these', 'components', 'is', 'emotion',
                    'nor', 'is', 'emotion', 'entity', 'that', 'causes', 'these', 'components',
                    '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$',
                    '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$',
                    '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$',
                    '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$',
                    '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$',
                    '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$',
                    '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$',
                    '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$',
                    '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$',
                    '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$',
                    '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$',
                    '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$',
                    '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$',
                    '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$',
                    '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$',
                    '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$',
                    '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$', '$PAD$']]

output = word2index(text, wordic)

print(output)


